### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by gonzalo-bulnes**
**When I** maintain the Dredd Hooks Ruby gem 
**I want** its dependencies to be up-to-date 
**So that** the maintenance tools keep being familiar to the Ruby community 
**And** it is easier for everyone to contribute

### CODE REVIEW

**Comment by gonzalo-bulnes** [comment]
**Note**: Since v0.6.2, [Aruba](https://github.com/cucumber/aruba/blob/v0.14.2/History.md) has undergone some changes that affect our test suite (starting from the 0.9.x series, STDOUT and STDERR cannot be checked for content as before). These changes will very likely be part of its **v1.0.0** release.

I didn't update Aruba it in this PR, but it is worth keeping an eye on it and start thinking about what these changes mean for us.

**Comment by honzajavorek** [comment]
@gonzalo-bulnes Thanks for bringing the changes in Aruba up!

**Comment by netmilk** [comment]
@hj @gonzalo-bulnes Guys, how we're going to coordinate the Aruba update across the entire Dredd hooks ecosystem?

**Comment by gonzalo-bulnes** [comment]
Hi @netmilk, @honzajavorek  what are your plans? I guess the entire Dredd hooks ecosystem is quite a few. I'm fine with following what you decide on you side. If you want to take a closer look together at what updating Aruba means concretely, let's have a talk about it. (Let's maybe start asynchronously? In https://github.com/apiaryio/dredd-hooks-ruby/issues/26 for example?)

**Comment by honzajavorek** [comment]
This is a tracking issue for porting the changes to each of the hook repositories: https://github.com/apiaryio/dredd-hooks-template/issues/16

**Pull request merged**
